add user_is_active to intermediate and mart
mitodl/ol-data-platform pull request #1016
Opened 2024-02-26 18:29 UTC by rachellougee

### What are the relevant tickets?

NA
Part of https://github.com/mitodl/hq/issues/3613

### Description (What does it do?)

This adds user_is_active to intermediate models - int__combined__users, int__edxorg__mitx_users , int__mitx__users and marts__combined__users 
- it doesn't filter out inactive users in intermediate to make sure we don't drop order and enrollment data for any inactive users 
- for marts__combined__users, not sure if it makes sense to filter inactive users. But for now I've added user_is_active and pull the correct email if the account exist on both edx.org and MITx Online. 

### How can this be tested?

```
dbt build --select int__edxorg__mitx_users
dbt build --select int__mitx__users
dbt build --select int__combined__users
dbt build --select marts__combined__users
```

2024-02-26 18:31 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/marts__combined__users.sql
>                  then user_mitxonline_email
there are some retired users on MITx Online, this is to make sure we don't use the hashed email for this
```
select * from ol_warehouse_production_mart.marts__combined__users
where user_mitxonline_username is not null and user_edxorg_username is not null
and user_email like 'retired%'
```

2024-02-27 15:34 UTC, KatelynGit requested changes

2024-02-27 15:34 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
I'm getting an error when I try to run the build here. We may need to make a change to the code. 

Database Error in test relationships_int__edxorg__mitx_courserun_enrollments_user_id__user_id__ref_int__edxorg__mitx_users_ (models/intermediate/edxorg/_int_edxorg__models.yml)
13:55:01    TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 20000 ms elapsed", query_id=20240227_135440_00179_aszsu)

2024-02-27 15:45 UTC, KatelynGit commented
Builds ran clean and definitions and tables looked good. Only issue I saw was the error running the int__edxorg__mitx_users build due to a relationship test.

2024-02-27 15:47 UTC, rachellougee commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
@KatelynGit I don't see any error when running ` dbt build --select int__edxorg__mitx_users --vars 'schema_suffix: rlougee' --target dev_production`. But based on what you posted here, its not related to this change. If you read the error, it points to this line https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml#L124

So I think you need to run `int__edxorg__mitx_courserun_enrollments`. Can you try that?

2024-02-27 15:57 UTC, KatelynGit approved these changes

2024-02-27 17:10 UTC, merged