create staging and intermediate models for OCW courses
mitodl/ol-data-platform pull request #1022
Opened 2024-03-08 16:36 UTC by rachellougee

### What are the relevant tickets?

https://github.com/mitodl/ol-data-platform/issues/493
and https://github.com/mitodl/hq/issues/3609

### Description (What does it do?)

Adds the OCW courses metadata related tables into data platform
 - stg__ocw__studio__postgres__websites_website
 - stg__ocw__studio__postgres__websites_websitecontent
 - stg__ocw__studio__postgres__websites_websitestarter
 - int__ocw__courses  (this table can be used for https://github.com/mitodl/hq/issues/3609)
 - int__ocw__course_topics (supporting table for OCW course topic in tabular format)
 - int__ocw__course_instructors (supporting table for OCW instructors metadata in tabular format)
 - int__ocw__course_departments (supporting table for OCW department number and name in tabular format)

### How can this be tested?

Run the following commands, tests should all pass
```
dbt build --select staging.ocw
dbt build --select intermediate.ocw
```

### Additional Context

I use https://github.com/mitodl/ocw-hugo-themes/blob/main/base-theme/data/departments.json to map department number to name since it's not maintained in database

2024-03-08 16:38 UTC, rachellougee commented on src/ol_dbt/macros/transform_code_to_readable_values.sql
> +---- https://github.com/mitodl/ocw-studio/blob/master/static/js/resources/departments.json
This is result of I renamed https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/macros/transform_user_profile_values.sql. The only change is to add this `transform_ocw_department_number` macro

2024-03-12 21:12 UTC, pdpinch requested changes

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +      list. e.g. Lecture Notes, Problem Sets with Solutions,...
For a case like this, where there's a long, controlled vocabulary, I'd love to have a link. But I don't think we have a nice place to link folks too, just the code at https://github.com/mitodl/ocw-hugo-projects/blob/049c85e6544a36ba69a89602e5014f6085ef8831/ocw-course-v2/ocw-studio.yaml#L163-L207

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +    tests:
This is an odd field name for the contents. Is this what it's called in the OCW source, @pt2302 ?

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +      description: str, short unique identifier for the OCW website.
@pt2302 is it worth mentioning that the short id is used for naming repos and folders on Google drive?

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +        description, course number, topics, etc.
It is too much to list out all the metadata fields that will be used in the intermediate tables, e.g. departments and instructors?

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +  - name: raw__ocw__studio__postgres__websites_websitecontent
question: are we importing all of the data in this table, or do we filter it somehow?

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_stg_ocw__models.yml
> +    description: str, unique name of the website. It appears as part of website url
```suggestion
  - name: website_name
    description: str, unique name of the website. It appears as part of OCW Studio urls
```

@pt2302 can you confirm my understanding here? I believe the website_name is only used in internal, Studio URLs.

2024-03-12 21:12 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_stg_ocw__models.yml
> +- name: stg__ocw__studio__postgres__websites_websitestarter
Do we need this?

2024-03-12 21:24 UTC, rachellougee commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +  - name: raw__ocw__studio__postgres__websites_websitecontent
We import all of the data, and then filter for [sitemetadata](https://github.com/mitodl/ol-data-platform/pull/1022/files#diff-cd9f079e3ff8fac1eb32162bfe434f12d4da1aff74e32f26aedb69eb747dff45R43) and [instructor](https://github.com/mitodl/ol-data-platform/pull/1022/files#diff-6f59831755214f83d1f96e6f4602fb53028346324915f486e4f5b7f8e683c037R14)

2024-03-12 21:26 UTC, rachellougee commented on src/ol_dbt/models/staging/ocw/_stg_ocw__models.yml
> +- name: stg__ocw__studio__postgres__websites_websitestarter
yes, this is used for filtering https://github.com/mitodl/ol-data-platform/pull/1022/files#diff-cd9f079e3ff8fac1eb32162bfe434f12d4da1aff74e32f26aedb69eb747dff45R44. There are a couple of records that are not ocw-course

2024-03-13 14:01 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +      e.g. 18.05-spring-2022
The source of this field is Short ID. It's not validated on the UI to be like this structure, but looking at the courses on production, they follow this convention. 
<img width="483" alt="Pasted Graphic 8" src="https://github.com/mitodl/ol-data-platform/assets/3138890/a7a124aa-2ee6-4f08-b400-803b6f91b3b5">

2024-03-13 14:02 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +      on OCW production.
This is calculated field https://github.com/mitodl/ol-data-platform/pull/1022/files#diff-a2ca1f103b5eb30861f741787220e2ad99b9a9f4cdf545c169c6d11d1f12677fR25

2024-03-13 14:13 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +    - not_null
Thank you for pointing that out. Looks like there are a few courses with empty string as course term ("term":"",), which explains why this test has passed as these are not null but empty string. I can make note of that.

2024-03-13 14:16 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +    description: str, course level in comma-separated list.  e.g. Undergraduate, Graduate
I can enumerate them all and add test for it. Yes, this is a controlled vocabulary (4 values)

2024-03-13 14:28 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +    tests:
I followed what's called in metadata and looks like its called title https://ocw-studio-rc.odl.mit.edu/sites/ocw-www/type/instructor/

2024-03-13 19:07 UTC, rachellougee commented
@pdpinch I think I answered and addressed your questions and comments. But let me know if anything I missed

2024-03-14 13:27 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +      e.g. 18.05-spring-2022
This is included as a identifier to OCW course just like other platforms we have [courserun_readable_id](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/intermediate/combined/_combined_models.yml#L85) . Otherwise, I don't know what other field would be appropriate for that.

2024-03-14 14:08 UTC, rachellougee commented on src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
> +      e.g. 18.05-spring-2022
Sorry, do you mean the naming or the value?  The value is taken exactly the same as short_id. The naming is probably better to follow what other platform is called as that's how we name it in bootcamp, xpro, mitxonline etc in intermediate. Unless we have a strong opinion on this.

2024-03-14 14:59 UTC, rachellougee commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +      description: str, short unique identifier for the OCW website.
I updated the source field description for short_id

2024-03-14 15:04 UTC, rachellougee commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +        description, course number, topics, etc.
I updated the description to mention the metadata fields used in intermediate and include the above link

2024-03-14 15:17 UTC, pdpinch approved these changes
one last comment. Feel free to merge after it's addressed.

2024-03-14 15:17 UTC, pdpinch commented on src/ol_dbt/models/staging/ocw/_ocw__sources.yml
> +        It is used for naming repos and folders on Google drive.
```suggestion
    - name: short_id
      description: str, short unique identifier for the OCW website. e.g. 18.05-spring-2022
        It is used for naming repos on github.mit.edu and folders on Google drive.
```

2024-03-14 15:37 UTC, merged