add a new combined programs mart
mitodl/ol-data-platform pull request #1038
Opened 2024-03-18 11:51 UTC by KatelynGit

### What are the relevant tickets?
https://github.com/mitodl/hq/issues/3765

### Description (What does it do?)
Adds a new marts__combined_program_enrollment_detail table that contains program, enrollment, and certificate data from xpro, mixonline, and edx.

### How can this be tested?
dbt build --select +marts__combined_program_enrollment_detail

2024-03-18 14:56 UTC, rachellougee requested changes
I left a few comments below, especially the uniqueness of this table. 

Also, based on the query in the mart, I believe we are missing old DEDP enrollments/certificates that only exist in MicroMasters. This also exposes data incomplete for DEDP enrollments in intermediate, so we may want to address that before creating this mart. 

Lastly, we should discuss whether we want all the program enrollments from edX.org be null. But that may be question for @pdpinch as well.

2024-03-18 14:56 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +        "programenrollment_created_on", "programcertificate_uuid"]
The uniqueness for this table shouldn't be all these 6 columns as that indicates we are missing some columns to be included in the mart. 
- For xPro, its unique on program, user and order. So we may want to bring in order here as without order, we can't tell why there are multiple enrollments for the same user and program
- For the rest, its unique on program_title and user_email

So if we want the uniqueness for the whole table, it should be program_title, user_email and order_id.

2024-03-18 14:56 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +      the MITOnline website or MITxPro website
`MITx Online`

2024-03-18 14:56 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/marts__combined_program_enrollment_detail.sql
> +        , edx_program_certificates.program_uuid as programcertificate_uuid
`program_uuid` can't be the programcertificate_uuid.  
- program_uuid is unique per program
- programcertificate_uuid is unique per certificate, not per program

For edx.org program certificate, there is no uuid from 2U data. But we can either generate one in intermediate if needed.

2024-03-25 20:51 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +        "programenrollment_created_on", "programcertificate_uuid"]
I've simplified this and removed columns but unfortunately I don't have order_id on the table so I had to use the timestamp in it's place but it does make it unique.

2024-03-25 20:51 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +      the MITOnline website or MITxPro website
fixed this thanks!

2024-03-25 20:51 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined_program_enrollment_detail.sql
> +        , edx_program_certificates.program_uuid as programcertificate_uuid
fixed this as well

2024-03-26 11:16 UTC, closed without merging

2024-03-26 11:46 UTC, KatelynGit commented
sorry had to close this... please see new PR https://github.com/mitodl/ol-data-platform/pull/1055