remove salesforce dbt models
mitodl/ol-data-platform pull request #1084
Opened 2024-04-18 18:00 UTC by KatelynGit

### Description (What does it do?)
Salesforce passwords have expired https://airbyte.odl.mit.edu/workspaces/3f0ccc59-baa3-4567-92e5-c61fb737467b/connections/ad3f786c-54b7-4aa9-a29e-521c3a47af72/job-history#8746::0
We need to pause that pipeline. This ticket is to remove all the staging and intermediate salesforce dbt models we currently have. This is an urgent need.

### How can this be tested?
Check to see all salesforce dbt models are now missing.

2024-04-18 18:10 UTC, blarghmatey requested changes
Rather than deleting these models entirely, it might be better to set them up in a `.dbtignore` so that they get skipped for the time being while maintaining the code in the repo. https://docs.getdbt.com/reference/dbtignore

2024-04-18 18:10 UTC, KatelynGit commented
Tobias I remove the models but all the code is saved. I'll put that elsewhere

2024-04-18 18:11 UTC, KatelynGit commented
> Rather than deleting these models entirely, it might be better to set them up in a `.dbtignore` so that they get skipped for the time being while maintaining the code in the repo. https://docs.getdbt.com/reference/dbtignore

o ok I can do that instead

2024-04-18 19:28 UTC, KatelynGit commented
@blarghmatey I've added a dbtignore file but since I've never done that before let me know if it looks ok to you

2024-04-19 16:21 UTC, KatelynGit commented
@blarghmatey I've removed the salesforce field from int__mitxpro__b2becommerce_b2border. I'll open a new issue with the exact code we previous had included so when we get sales force back it'll be an easy change just to add it back.

2024-04-22 14:06 UTC, rachellougee approved these changes

2024-04-22 14:06 UTC, rachellougee commented on src/ol_dbt/.dbtignore
> +_int_salesforce__models.yml
It can be directories instead of listing all the files. Either way would work.
```
models/staging/salesforce
models/intermediate/salesforce
```

2024-04-22 16:08 UTC, merged