staging edxorg course enrollment and grade
mitodl/ol-data-platform pull request #1107
Opened 2024-05-02 19:24 UTC by rachellougee

### What are the relevant tickets?

Part of https://github.com/mitodl/hq/issues/4067, the rest of the raw tables mentioned in the issue are not ready yet

### Description (What does it do?)

Adding `stg__edxorg__s3__courserun_grade` and `stg__edxorg__s3__courserun_enrollment` 
  - fields are converted to the proper data types as raw fields are all ingested as string
  - data is deduplicated

### How can this be tested?

 dbt build --select stg__edxorg__s3__courserun_enrollment
 dbt build --select stg__edxorg__s3__courserun_grade

2024-05-02 19:27 UTC, rachellougee commented on src/ol_dbt/macros/apply_deduplication_query.sql
> +{% macro deduplicate_query(cte_name1='source', cte_name2='most_recent_source', partition_columns='id') %}
The change here doesn't affect the existing models that are currently using this as `id` is the default option

2024-05-03 00:59 UTC, KatelynGit reviewed
The builds all looked good I just left some comments on the descriptions

2024-05-03 00:59 UTC, KatelynGit commented on src/ol_dbt/models/staging/edxorg/_stg__edxorg__models.yml
> +  - name: courserunenrollment_is_active
It looks like this is showing up as an integer in the table when created instead of a string. I'd also specify in the description that this will be a 1 or a 0 value.

2024-05-03 00:59 UTC, KatelynGit commented on src/ol_dbt/models/staging/edxorg/_stg__edxorg__models.yml
> +    description: timestamp, time when this enrollment was created
I'd change it to: 
 description: timestamp, time and date when this enrollment was created

2024-05-03 00:59 UTC, KatelynGit commented on src/ol_dbt/models/staging/edxorg/_stg__edxorg__models.yml
> +    description: timestamp, time when the course grade was first calculated for this
I'd change it from "time" to "time and date" for timestamp descriptions on this table

2024-05-03 13:04 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/_stg__edxorg__models.yml
> +  - name: courserunenrollment_is_active
I think this should be `boolean` to be consistent with other data sources like mitxonline. So I cast to boolean instead of integer.

2024-05-03 13:05 UTC, rachellougee commented
@KatelynGit Thanks for the review. It should be all set. But let me know anything else for the description

2024-05-03 16:20 UTC, KatelynGit requested changes
Looks good

2024-05-03 16:23 UTC, merged