Create staging_guidelines.md
mitodl/ol-data-platform pull request #344
Opened 2022-09-27 14:04 UTC by dseaton

Proposed guidelines associated with the "staging" process.

## Motivation and Context
These guidelines are intended to help reduce ambiguity as we stage data in our dbt project.

2022-09-27 14:37 UTC, abeglova requested changes

2022-09-27 14:37 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
I don't think this is a good idea. More verbose column names are harder to remember, tyoe and work with. I think if there is ambiguity we can add table prefixes in the intermediate layer. It is is pretty easy to check the type in the database and the only situations where ambiguous types really cause issues in sql queries is surprise nulls and errors in converting between types (ei converting between string timestamps and dates). Also all the dates are stored as iso string anyway. I do like the is_ prefix for booleans

2022-09-27 14:37 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +dbt has a [robust testing framework](https://docs.getdbt.com/docs/building-a-dbt-project/tests) that includes four
I don't see the point of this either. The transformations we do in the staging layer generally won't introduce the kinds of errors that can be caught by dbt tests. We can check that all the primary keys are  unique and present but if they are not the problem is either in the original data or in copying the raw files. I agree that we should have tests to check that we aren't accidentally dropping or creating rows in the intermediate and mart layers

2022-09-27 14:54 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +dbt has a [robust testing framework](https://docs.getdbt.com/docs/building-a-dbt-project/tests) that includes four
For the task at hand (bringing over postgres tables), your logic is spot on. I don't know about cases with more complex data (e.g., log events), or data that we don't directly own (e.g., IRx data), but we aren't there yet. A good compromise is:

"Test any field value transformations you make". So if you change a couple boolean fields to a single categorical field, we would write a test for that.

2022-09-27 15:27 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
> add table prefixes in the intermediate layer

dbt guidelines: [Rename and Cast Fields Once (in the staging layer)](https://docs.getdbt.com/guides/legacy/best-practices#rename-and-recast-fields-once).

> More verbose column names are harder to remember, type and work with.

My take on Emily's recommendations are: 1) interpretability by analysts, data scientists, consumers and 2) settling on a reproducible convention so we don't have to ask each other about naming practices (especially when multiple people are working on a single dbt project). 

It might seem like overhead to create <type>_<entity>_<col_name/details>, but it will save a lot of overhead in other places. For example, by leaving "staging" models with the original names, it means that an analyst working in the intermediate layer has to remember 1) the original names and 2) the naming conventions.

2022-09-27 15:45 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
I think adding the table name to the prefix will make it more confusing not less down the line. Once you are joining data from  multiple databases it's not clear which "user" table you are talking about and preserving the database structure of the original source in the name makes things more confusing not less. For example, once I'm working with intermediate data I don't need to remember that the mitxonline postgress database stores first name in the user_legaladdress table and not users_user

2022-09-27 16:56 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
> I think adding the table name to the prefix will make it more confusing not less down the line.

We will have to get deeper in the work, or create a couple examples in Redash, in order to test out Emily's codification. It's not meant to be just a table name.

> As for types - Maybe we actually add dbt tests to ensure that the types are what we expect them to be? That sounds a lot easier to work with than adding prefixes

I am less certain on "types", but predict it will serve everyone well in the future. Especially when we do more complex staging work and when we get to marts that require specific aggregation (other measures).

2022-09-27 17:04 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
I don't think type mismatches cause problems in sql queries very often and more verbose and less readable names do add to confusion

2022-09-27 17:09 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
And the kind of problems that are caused by something being not the type you expect in a sql query would be caught immediately anyway

2022-09-27 17:15 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
I'm just worried that column names will work similarly to the prefixes for table names which are descriptive but also pretty much make it impossible to get the correct table name without copy pasting

2022-09-27 18:38 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
I am going to put together a couple more examples to demonstrate how this would work. I have realized that I misinterpreted part of Emily's suggestions with `txt`, which may have led to more confusion. Stay tuned.

2022-09-27 18:54 UTC, pdpinch commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
Anastasia has done a lot of work with writing reports in redash, and I expect she'll be doing more. I trust her experience with column names. 

And we can change it later if we have to, right?

2022-09-27 20:02 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
@pdpinch I added a contextual statement to the PR. [See above](https://github.com/mitodl/ol-data-platform/pull/344#issue-1387828038).

2022-09-28 17:26 UTC, abeglova commented on src/ol_dbt/docs/staging_guidelines.md
> +dbt has a [robust testing framework](https://docs.getdbt.com/docs/building-a-dbt-project/tests) that includes four
So I thought about this and I changed my mind. We shouldn't write tests for the sake of writing tests but it's important to documents unique and non-null constraints from the original database somewhere in ol-data-platform and dbt tests seems like an easy way to do it. 

For example in the user prs I'm working on,  it's critical information that  the mitxonline enforces that `email` and `username` are  unique for users and the user_legaladdress table is one to one with users (so user_id in that table is unique). We can document that information by adding tests for it.

2022-09-28 18:09 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +dbt has a [robust testing framework](https://docs.getdbt.com/docs/building-a-dbt-project/tests) that includes four
I like it. Will update language and use your email/username example.

2022-10-04 21:00 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +- username: `txt_user_username`
@abeglova This should be all set. My updates say "discuss naming conventions in the issue".

2022-10-04 21:01 UTC, dseaton commented on src/ol_dbt/docs/staging_guidelines.md
> +dbt has a [robust testing framework](https://docs.getdbt.com/docs/building-a-dbt-project/tests) that includes four
@abeglova This should be all set. State that we should test fields that will be used in intermediate/mart layers.

2022-10-05 15:45 UTC, abeglova approved these changes
LGTM

2022-10-05 19:44 UTC, merged