MicroMasters users
mitodl/ol-data-platform pull request #448
Opened 2022-11-15 17:07 UTC by rachellougee

## Description

Staging and intermediate users model for MicroMasters
stg__micromasters__app__postgres__auth_user
stg__micromasters__app__postgres__auth_usersocialauth
stg__micromasters__app__postgres__profiles_profile
int__micromasters__users (adding a field to match with mitxonline users)

## Motivation and Context
https://github.com/mitodl/ol-data-platform/issues/443

## How Has This Been Tested?
Ran `dbt run` 
and the following commands:
`dbt test --select stg__micromasters__app__postgres__auth_user`
`dbt test --select stg__micromasters__app__postgres__auth_usersocialauth`
`dbt test --select stg__micromasters__app__postgres__profiles_profile`
`dbt test --select int__micromasters__users`

(Note that there are a few errors related to the MITxOnline programcertificate when running a full 'dbt test` because duplicates exist in 'raw__mitxonline__app__postgres__courses_programcertificate` Tobias said it's related to the S3 connector they are working on)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2022-11-15 18:18 UTC, Ferdi commented
> int__micromasters__users (adding a field to match with mitxonline users)

Can you elaborate a bit about *adding a field to match with mitxonline users*

The main reason we are bringing MM users is to be able to augment the users/profiles of learners from edx.org and mitxonline.

2022-11-15 18:34 UTC, rachellougee commented
> int__micromasters__users (adding a field to match with mitxonline users)

> Can you elaborate a bit about adding a field to match with mitxonline users
> 
> The main reason we are bringing MM users is to be able to augment the users/profiles of learners from edx.org and mitxonline.

I am simply adding a field 'user_mitxonline_username' to the MM users intermediate table so that it could be used for matching MITxOnline users (currently no profile in MITxOnline). It is not limited to MITxOnline users, just a separate field for later use

2022-11-15 18:40 UTC, Ferdi commented
> user_mitxonline_username

Is this specifically for matching with mitxonline users?  Lots of useres in MM come from edx.org.  we might want to match with those profiles as well.

2022-11-15 18:52 UTC, rachellougee commented
> Is this specifically for matching with mitxonline users? Lots of useres in MM come from edx.org. we might want to match with those profiles as well.

Yes, this field is specifically for matching mitxonline users. I can add another field if we want to match it with edx.org

2022-11-16 15:59 UTC, abeglova requested changes
Back to you with a few comments. Also, it probably makes sense to add a intermediate model with mitxonline data joined to MM profile data, since that was the motivation for importing this data

2022-11-16 15:59 UTC, abeglova commented on src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__profiles_profile.sql
> +            when edx_level_of_education = 'hs' then 'High school'
I think it makes sense to standardize this with the xpro education levels https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml#L612.

2022-11-16 15:59 UTC, abeglova commented on src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__profiles_profile.sql
> +            when edx_level_of_education = 'hs' then 'High school'
Also either rename the column to user_highest_education or rename the column in xpro

2022-11-16 15:59 UTC, abeglova commented on src/ol_dbt/models/staging/micromasters/_micromasters__sources.yml
> +    - name: edx_job_title
Looks like there are lots of columns here that you did not include in the staging data. Is that because those columns are blank? Or PII concerns? For xpro we included all the profile data in the staging table but not the intermediate tables

2022-11-16 20:19 UTC, rachellougee commented on src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__profiles_profile.sql
> +            when edx_level_of_education = 'hs' then 'High school'
Renamed it.
(I was hesitant to rename this field to user_highest_education, but if we want to be consistent with xpro, then makes sense)

2022-11-16 20:20 UTC, rachellougee commented on src/ol_dbt/models/staging/micromasters/_micromasters__sources.yml
> +    - name: edx_job_title
I added all the fields to the staging

2022-11-16 20:21 UTC, rachellougee commented
@abeglova Please take a look. I've also added the MM profile to intermediate, so that it's available to pull from.

2022-11-16 20:47 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxonline/int__mitxonline__users.sql
>      , users.user_is_active
Maybe add users_profiles.user_profile_id here?

2022-11-16 20:47 UTC, abeglova commented on src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__profiles_profile.sql
> +            when edx_level_of_education = 'hs' then 'High school'
It probably makes sense to rename the labels to

"Secondary/high school", "Junior secondary/junior high/middle school" "Elementary/primary school"

to match xpro as well. Either that, or change the xpro levels to be less wordy.

2022-11-16 20:50 UTC, abeglova approved these changes
Two small comments, otherwise LGTM

2022-11-16 20:51 UTC, rachellougee commented on src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__profiles_profile.sql
> +            when edx_level_of_education = 'hs' then 'High school'
so I don't know if we should change the value to match with xpro.
These options are taken from MicroMasters app, if we change it, it's not how user chose when they sign up
```
    LEVEL_OF_EDUCATION_CHOICES = (
        (DOCTORATE, 'Doctorate'),
        (MASTERS, "Master's or professional degree"),
        (BACHELORS, "Bachelor's degree"),
        (ASSOCIATE, "Associate degree"),
        (HIGH_SCHOOL, "High school"),
        (JUNIOR_HIGH_SCHOOL, "Junior high school"),
        (ELEMENTARY, "Elementary school"),
        (NO_FORMAL_EDUCATION, "No formal education"),
        (OTHER_EDUCATION, "Other education"),
    )
```

2022-11-16 20:56 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/int__mitxonline__users.sql
>      , users.user_is_active
I am not sure the purpose of adding user_profile_id here ?  it might cause confusion as that's not MITxOnline profile id. I made CTL users_profiles here so we can add any field from the MM profile as the data is already matched at this point.

2022-11-16 21:03 UTC, abeglova reviewed
Back to you with a few comments. Also, it probably makes sense to add a intermediate model with mitxonline data joined to MM profile data, since that was the motivation for importing this data

2022-11-16 21:03 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxonline/int__mitxonline__users.sql
>      , users.user_is_active
Maybe add it as micromasters_profile_id then? The idea is that we want queries that are using the intermediate tables as inputs can easily join to that data

2022-11-16 21:37 UTC, rachellougee commented
added `user_micromasters_profile_id`. and the test ran fine

2022-11-16 21:58 UTC, merged