mitxpro ecommerce
mitodl/ol-data-platform pull request #499
Opened 2022-12-20 15:02 UTC by abeglova

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-12-20 22:38 UTC, rachellougee requested changes
Just a couple of comments, otherwise looks good

2022-12-20 22:38 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml
> +        the line Currently orders have exactly one line
"Currently orders have exactly one line" is this correct?

2022-12-21 14:19 UTC, abeglova commented on src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml
> +        the line Currently orders have exactly one line
Thanks for the catch, this was copied over from mitxonline

2022-12-21 15:02 UTC, rachellougee approved these changes
👍

2022-12-21 15:02 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
> +      the line Currently orders have exactly one line
Just one more to remove

2022-12-21 16:00 UTC, merged