add edx user course activities model
mitodl/ol-data-platform pull request #550
Opened 2023-02-01 15:05 UTC by rachellougee

## Description

This PR adds the following user course activities fields from edx BigQuery table `person_course` to staging and intermediate model - int__edxorg__mitx_user_courseactivities:

courseactivitiy_num_events
courseactivitiy_num_activity_days
courseactivitiy_num_progress_check
courseactivitiy_num_problem_check
courseactivitiy_num_show_answer
courseactivitiy_num_show_transcript
courseactivitiy_num_seq_goto
courseactivitiy_num_play_video
courseactivitiy_num_seek_video
ourseactivitiy_num_pause_video
courseactivitiy_num_video_interactions
courseactivitiy_num_unique_videos_viewed
courseactivitiy_total_videos_watched
courseactivitiy_average_time_diff_in_sec
courseactivitiy_standard_deviation_in_sec
courseactivitiy_max_diff_in_sec
courseactivitiy_num_consecutive_events_used
courseactivitiy_total_elapsed_time_in_sec

## Motivation and Context

https://github.com/mitodl/ol-data-platform/issues/548

## How Has This Been Tested?

TBD (can't test on QA at the moment)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-02-03 14:04 UTC, pdpinch commented
You said in https://github.com/mitodl/hq/discussions/579#discussioncomment-4845718 that this is blocked by a PR from Tobias. Which PR is that?

2023-02-13 15:40 UTC, rachellougee commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> -      compare_model: ref('stg__edxorg__bigquery__mitx_person_course')
We can't really compare intermediate grades with person_course because there are users who only exist in person_course, not user_info_combo. These will be dropped with inner join to users.

2023-02-14 02:42 UTC, Ferdi commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , viewed as courseactivitiy_viewed
visited_once ?

2023-02-14 02:42 UTC, Ferdi commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , explored as courseactivitiy_explored
viewed_half ?

2023-02-14 02:42 UTC, Ferdi commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nevents as courseactivitiy_num_events
'number of something' is common . Do we usually use 'num'  ? or nr?

2023-02-14 02:42 UTC, Ferdi commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nvideos_total_watched as courseactivitiy_total_videos_watched
is this 'percentage o video watched' https://github.com/MIT-IR/simeon/blob/main/simeon/upload/schemas/schema_person_course.json#L331 ?

2023-02-14 13:53 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nvideos_total_watched as courseactivitiy_total_videos_watched
yes, it's calculated like this : safe_divide(count(*), n_total_videos), the value is between 0 to 1. I can rename it as percentage_total_videos_watched?

2023-02-14 13:53 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , viewed as courseactivitiy_viewed
yes, sounds good to me

2023-02-14 13:53 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nevents as courseactivitiy_num_events
I see we use num_courses, num_runs in our application, so I just follow these patterns.

2023-02-14 14:09 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nevents as courseactivitiy_num_events
But I can rename these to number_of_x

2023-02-14 14:38 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_person_course.sql
> +        , nevents as courseactivitiy_num_events
actually, number_of is too lengthy, I think num is more commonly used.

2023-02-14 16:23 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> -      compare_model: ref('stg__edxorg__bigquery__mitx_person_course')
Do you know why those users do not exist in user_info_combo? Is it something like discontinued accounts due to cheating/spam so dropping them makes sense? Or just missing data issues?

2023-02-14 16:29 UTC, abeglova requested changes
Mostly lgtm but I had a few questions

2023-02-14 16:29 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> +  - dbt_expectations.expect_compound_columns_to_be_unique:
Should we expect this table to have the same number of rows as person_course?

2023-02-14 16:29 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> +      MITProfessionalX, MITx, MITxPRO
Does it make sense to add a `accepted_values` test here?

2023-02-14 16:29 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> -      compare_model: ref('stg__edxorg__bigquery__mitx_person_course')
Does it make sense to use a left join instead?

2023-02-14 16:51 UTC, rachellougee commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> -      compare_model: ref('stg__edxorg__bigquery__mitx_person_course')
For these users who only exist in person_course but not user_info_combo, they are historical accounts that are no longer in the edx data package (I asked Jon about this a while ago). their data were in old courses


1 | MITx/14.73x/2013_Spring |  
2 | MITx/6.00x/2012_Fall |  
3 | MITx/6.00x/2013_Spring |  
4 | MITx/2.01x/2013_Spring |  
5 | MITx/16.101x/2013_SOND |  
6 | MITx/3.091X/2013_Fall |  
7 | MITx/6.00.1x/3T2013 |  
8 | MITx/7.00x/2013_Spring |  
9 | MITx/3.091x/2013_Spring |  
10 | MITx/3.091x/2012_Fall |  
11 | MITx/6.002x/2012_Fall |  
12 | MITx/8.MReV/2013_Summer |  
13 | MITx/6.BDx/1T2014

We could change it to left join, but the questions is do we need these if their accounts don't exist?
Also I believe we use INNER JOIN users for other data sources data, do we need to make LEFT JOIN for edx?

2023-02-14 16:53 UTC, rachellougee commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> +  - dbt_expectations.expect_compound_columns_to_be_unique:
This is the same issue as my comments above on users "who only exist in person_course but not user_info_combo"

2023-02-14 16:53 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> -      compare_model: ref('stg__edxorg__bigquery__mitx_person_course')
ok, its few enough users that we probably don't need to worry about it

2023-02-14 16:55 UTC, rachellougee commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> +      MITProfessionalX, MITx, MITxPRO
technically I could add accepted_values to a fixed list, but I am also not sure if IRx will add more institutions here as it's a free text in the sources that we don't have control over.

2023-02-14 17:02 UTC, abeglova commented on src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
> +  - dbt_expectations.expect_compound_columns_to_be_unique:
got it

2023-02-14 17:02 UTC, abeglova approved these changes
lgtm

2023-02-14 19:39 UTC, merged