Add mitxonline_username and edxor_username to MITx combined user
mitodl/ol-data-platform pull request #674
Opened 2023-05-01 21:43 UTC by rachellougee

## Description

This PR adds both `user_mitxonline_username` and `user_edxorg_username` to `int__mitx__users`.
It doesn't dedupe users who have accounts on both MITx Online and edX.org based on their linked profile from MicroMasters. However, with these two fields, it can easily find out which user from MITx Online is the same user on edX.org when querying `where user_edxorg_username is not null and user_mitxonline_username is not null`

## Motivation and Context

No issue was created. This was from our data platform meeting today

## How Has This Been Tested?

 `dbt run --select int__mitx__users  --var 'schema_suffix: rlougee' --target dev_production`
 `dbt test --select int__mitx__users  --var 'schema_suffix: rlougee' --target dev_production`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- x ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-05-02 20:29 UTC, abeglova requested changes

2023-05-02 20:29 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitx/int__mitx__users.sql
> +, mitx_users_dups_combined as (
So this query works but it is a little complicated could you do a full outer join from mitxonline_users to edxorg_users? Or am I missing something?

2023-05-02 20:37 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitx/int__mitx__users.sql
> +, mitx_users_dups_combined as (
This query is to combine user profiles IF users exist on MITx Online and edX.org, INNER JOIN here does the trick, not sure what we try to do by changing to full outer joins. Let me know if I misunderstand

2023-05-03 12:59 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitx/int__mitx__users.sql
> +    left join mitxonline_users on mitxonline_users.user_edxorg_username = edxorg_users.user_username
I don't think you need the left join anymore here or in line 31

2023-05-03 14:57 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitx/int__mitx__users.sql
> +    left join mitxonline_users on mitxonline_users.user_edxorg_username = edxorg_users.user_username
Done. Removed left joins

2023-05-03 15:27 UTC, abeglova approved these changes
lgtm

2023-05-03 21:58 UTC, merged