Add files via upload
mitodl/ol-data-platform pull request #753
Opened 2023-07-10 10:57 UTC by KatelynGit

This adds 2 new mart tables marts__mitxpro_ecommerce_userorder_details and marts__mitxpro_ecommerce_productcoupon_details

# What are the relevant tickets?
https://bi.odl.mit.edu/queries/983 
https://bi.odl.mit.edu/queries/1012 

# Description (What does it do?)
creating data mart tables as described in https://github.com/mitodl/hq/issues/1803

# How can this be tested?
Run the following commands against your schema or QA
Run dbt build --select marts.mitxpro if you have all intermediate models, otherwise add + in front of marts.mitxpro to run upstream models

2023-07-10 19:08 UTC, abeglova requested changes

2023-07-10 19:08 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +    , ecommerce_productcouponassignment.product_id
This table is supposed to be usable to end users so you should include information about the course run/program that is the product

2023-07-10 19:08 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_userorder_details.sql
> +inner join couponpaymentversion
I don't think all orders use coupons, so this is excluding the orders where ecommerce_order.couponpaymentversion_id is null

2023-07-10 19:08 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_userorder_details.sql
> +    , b2becommerce_b2border.product_id
Again this is meant to be used by end users so  coupon_id/product_id/order_id won't be useful information for them

2023-07-10 19:15 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +    , ecommerce_productcouponassignment.product_id
I think the product id people want to see is the readable id of the course run/program that the ecommerce_product record is associated with

2023-07-10 19:44 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productcouponassignment
So b2b coupons don't have a ecommerce_productcouponassignment which is why https://bi.odl.mit.edu/queries/983/source has the union

2023-07-11 16:47 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml
> +models:
removed additional 'models:' text

2023-07-11 19:58 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +    , ecommerce_productcouponassignment.product_id
I haven't included any course or program info in the table so far. This would require new joins to other tables with very different data. If we need it I'll add it but may have to research and add as a separate table maybe.

2023-07-11 19:58 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_userorder_details.sql
> +inner join couponpaymentversion
changed to a left join thanks

2023-07-11 19:59 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_userorder_details.sql
> +    , b2becommerce_b2border.product_id
I only added these so they could join between the two tables but I agree alone they are not useful

2023-07-12 14:10 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productcouponassignment
That's definitely good to know. For the other marts__mitxpro_ecommerce_userorder_details table we're pulling in the b2b order data that doesn't have a product coupon assignment and I've adjusted the  marts__mitxpro_ecommerce_productcoupon_details to use a left join to the product coupon assignment as well so hopefully that covers the issue.

2023-07-12 14:46 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +    , ecommerce_productcouponassignment.product_id
Talked it over Anastasia and we'll add the additional tables and fields and I'll re-commit

2023-07-12 18:02 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
You should join directly to courses_courserun and courses_program instead

2023-07-12 18:04 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
Is this why you needed the max()?

2023-07-14 13:06 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
The only table with the productversion_readable_id they requested is on the product version table so I had to pull that in unfortunately. And I don't see a join to product version through courses_courserun and courses_program. to eliminate duplicate rows I had a query above that one to filter them out - 
ecommerce_productversion as (
    select 
        product_id
        , productversion_readable_id 
    from productversion 
    where productversion_readable_id is not null
) 
The max piece was just handling a few records where we had multiple

2023-07-14 15:58 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
So I don't think you need productversion_readable_id (unless I missed where someone specifically asked for it) You need courserun_readable_id or product_readable id from the courserun or program tables/

2023-07-14 15:59 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
Taking the max is wrong anyway, since the latest product version is not nessesarily the correct one

2023-07-14 16:01 UTC, abeglova commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
And if the productversion_readable_id (I'm not sure if it does) changes between product versions you
'll have a row for each one

2023-07-20 13:08 UTC, KatelynGit commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productcoupon_details.sql
> +left join ecommerce_productversion
this field is needed per https://github.com/mitodl/hq/issues/1803 but new tables created instead so resolving this for now

2023-07-20 16:40 UTC, abeglova requested changes
I wasn't able to run the query - still figuring out if it gives the right results

2023-07-20 16:40 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join ecommerce_couponpaymentversion as ecommerce_couponpaymentversion
The as here is redundant

2023-07-20 16:40 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join couponversion as couponversion
couponversion is never defined should this be ecommerce_coupon version?

2023-07-20 16:40 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    ) as couponpaymentversion
This code is broken -  int__mitxpro__ecommerce_couponpaymentversion is never defined should id be ecommerce_couponpaymentversion? Also can the named subquery be defined before this query and called something other than couponpaymentversion since you are joining to ecommerce_couponpaymentversion?

2023-07-20 16:40 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +select
It would be helpful if you break this out into two named queries to make it clear that there are seperate subqueries for b2becommerce coupons and other coupons

2023-07-20 16:44 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    ) as couponpaymentversion
Maybe max_couponpaymentversion? But also why are you getting a max by couponpayment_name and not couponpayment_id?

2023-07-20 16:53 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    ) as couponpaymentversion
I guess the grouping is ok since the couponpayment_name is unique and non_null https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml#L463 and functionally an id

2023-07-20 17:48 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join ecommerce_couponpaymentversion as ecommerce_couponpaymentversion
I'll remove this

2023-07-20 17:50 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join couponversion as couponversion
yes ill change it

2023-07-20 17:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    ) as couponpaymentversion
I changed it from int__mitxpro__ecommerce_couponpaymentversion to ecommerce_couponpaymentversion.  And changed the title to max_couponpaymentversion for the subquery.

2023-07-21 11:54 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +select
to make this clear i added a field called combinedcoupon_table_source to show which data is which

2023-07-24 16:02 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    on coupon.coupon_id = b2b_ecommerce_b2border.b2bcoupon_id
This join is not correct b2bcoupon_id refers to theint__mitxpro__b2becommerce_b2bcoupon table not theint__mitxpro__ecommerce_coupon table

2023-07-24 17:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    , 'regular coupon'
fixed this i'll upload the latest

2023-07-24 17:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    , 'b2b coupon'
fixed this i'll upload the latest

2023-07-24 17:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +from b2b_ecommerce_b2border as b2b_ecommerce_b2border
fixed this i'll upload the latest

2023-07-24 18:02 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +left join ecommerce_couponversion
fixed and uploading soon

2023-07-24 18:18 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +left join b2b_ecommerce_b2border
I removed it updating soon

2023-07-24 18:18 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    on coupon.coupon_id = b2b_ecommerce_b2border.b2bcoupon_id
remove this join per other comments

2023-07-25 11:20 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    select distinct
i added a comment to the code explaining this

2023-07-25 13:28 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    , ecommerce_couponpaymentversion.couponpaymentversion_discount_amount
Instead of grouping 15+ fields in one query, could we break it down using CTEs with only required columns in the grouping first before passing it down to this query? I think it's both for readability and performance concerns. Just a suggestion.

2023-07-26 18:40 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    , ecommerce_couponpaymentversion.couponpaymentversion_discount_amount
I made the change to break it down a bit using CTEs

2023-07-26 19:25 UTC, KatelynGit commented
I've made the requested changes, compared to the bi query and looks good so far. It's ready for review

2023-07-26 19:38 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
It looks like you are grouping by every single field in this query? Can you remove the group by entirely?

2023-07-26 19:39 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I think you're essentially getting unique?

2023-07-26 19:40 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        b2b_ecommerce_b2border.b2border_email
I think you are grouping by every field here too?

2023-07-26 19:42 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    select distinct
I don't see the comment. Also, could you please not mark past comments as resolved?

2023-07-26 19:42 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    select distinct
It makes it hard to check if previous issues were addressed in your update

2023-07-27 12:29 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
Yes, that's correct I'm getting unique. If I remove the group by I'd get a bunch of duplicates in the table.

2023-07-27 12:29 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        b2b_ecommerce_b2border.b2border_email
Yes, that's right

2023-07-27 13:44 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
Ok so you can use the distinct keyword instead of grouping by every single column. But also the fact that you need to is a code smell - do you know which one of the joins is creating the duplicate rows?

2023-07-27 13:50 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
Could you get rid of the group by/distinct by changing the order of the joins?

2023-07-27 13:51 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
It's a bunch of them but I'm basically joining down from coupon to more detailed tables(different grain) to pull some of the requested fields and it causes dups.

2023-07-27 13:56 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
As far as I know changing the order would still result in dups unfortunately

2023-07-27 13:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I can definitely change it to distinct though that'll work great

2023-07-27 14:02 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
:( Ok let me see if I can rewrite this - this is definitely not ok to merge as is

2023-07-27 14:05 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I don't know if there's much to be re-written...there was basically a list of fields and we were told to create a big denormalized table...this is it...but definitely open to ideas

2023-07-27 14:05 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I think that's why the original bi query had a separate subquery for coupons with no redemptions - so the query could join from redemptions back to coupons in a way that doesn't create duplicates

2023-07-27 14:07 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
yea we can get rid of duplicated different ways but probably same results

2023-07-27 14:14 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
You get why the fact that you are doing a distinct there is a problem, right...

2023-07-27 14:18 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
Like for readability/maintainability of this query

2023-07-27 14:24 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I think part of the problem is I was told to add even lower grain fields not part of the bi query...but I don't know of a way to do it without a distinct definitely open to ideas though

2023-07-27 14:50 UTC, abeglova commented
Looks like there are a bunch of coupons that are showing up as duplicates once in the b2b subquery and once in the regular subquery - For example  coupon_codes  269152f683c84636976fa66eede3a322 and f984451b4b6245ec802525b63acd4bf0 but there are lots more. If you check the bi query those appear only once

2023-07-27 14:53 UTC, KatelynGit commented
Yes that's true I believe it's because we're pulling more fields from lower grain tables

2023-07-27 15:03 UTC, abeglova commented
SELECT coupon_code
FROM "ol_data_lake_production"."ol_warehouse_production_abeglova_intermediate"."int__mitxpro__ecommerce_combinedcoupons"
where combinedcoupon_table_source = 'regular coupon'
and couponpaymentversion_coupon_type = 'single-use'
group by coupon_code
having count(*) > 1

Returns 606 rows

2023-07-27 17:28 UTC, KatelynGit commented
> SELECT coupon_code FROM "ol_data_lake_production"."ol_warehouse_production_abeglova_intermediate"."int__mitxpro__ecommerce_combinedcoupons" where combinedcoupon_table_source = 'regular coupon' and couponpaymentversion_coupon_type = 'single-use' group by coupon_code having count(*) > 1
> 
> Returns 606 rows

I changed a left join to an inner to eliminate most of the extra records but some are due to data differences since the table isn't at a coupon grain

2023-07-27 18:06 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join productcouponassignment
Ok - in addition to the fact that this shouldn't be an inner join because not every coupon has a product assignment

there is one coupon code with more than one product coupon assignment. That coupon should not appear in the report twice with different product ids

2023-07-27 18:10 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    left join payment_transactions
So this join is one of the ones causing duplicates - Prior to this you had a uniqecouponpaymentversion_id per line (except for the weird edge case with productcouponassignment) Now you are joining every order associated with the coupon to every payment transaction associated with the coupon even when those are not matching

2023-07-27 18:11 UTC, abeglova commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    left join payment_transactions
This creates lines in your report with junk data

2023-07-27 18:15 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +    inner join productcouponassignment
ok switched it back to a left join

2023-07-27 18:46 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +, reg_coupon_fields as (
I couldn't find any joins causing issues but I'm look at the counts as each one is added

2023-07-28 18:41 UTC, KatelynGit commented
I deployed a new version of the table without distincts/groupbys except for one section where there is aggregation. You may still find multiple records for one coupon but they are different coupons versions and previous versions can be filtered out at a report level. I think it looks good let me know if you see any issues.

2023-07-28 21:26 UTC, rachellougee requested changes
I left a few comments, I also checked a couple of coupons, data don't seem to match with BI. 

e.g. coupon_code ='efcafaa7868f4d5691ce38a4a41fa092'. 
- It should has order_id 26329, but its null in`int__mitxpro__ecommerce_combinedcoupons`.  
- There are two rows in `int__mitxpro__ecommerce_combinedcoupons` for this coupon_code as regular coupon, but there should be just 1 row with `program-v1:xPRO+SysEngx`
 
![image](https://github.com/mitodl/ol-data-platform/assets/3138890/c7d22f9d-03cb-4c1e-ac8d-ae399ff4965a)

2023-07-28 21:26 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        on coupon.coupon_id = ecommerce_couponversion.coupon_id
These two joins don't seem to match with BI, can you confirm if this is the correct join condition? `couponpaymentversion_id` to `coupon_id` is 1 to many, On BI,`coupon` to `couponpayment` joined on `couponpayment_id`, not via `coupon_id`

2023-08-01 10:47 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
Changing this causes errors: L: 177 | P:  68 | RF02 | Unqualified reference 'omit' found in select with more
                       | than one referenced table/view.
                       | [references.qualification]
L: 177 | P:  73 | RF02 | Unqualified reference 'quotes' found in select with more
                       | than one referenced table/view.
                       | [references.qualification]

2023-08-01 10:48 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        , try_cast(ecommerce_order.order_state as BigInt) as combined_order_state
I'll fix this

2023-08-01 10:53 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        on coupon.coupon_id = ecommerce_couponversion.coupon_id
This is the correct order it produced the same results

2023-08-01 12:35 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
Take a look at the usage of https://trino.io/docs/current/functions/json.html#json-query and syntax, I used it for tracking log and it worked great, not sure why it would throws error if the original query is manually replacing the quote. I can take a look later

2023-08-01 14:10 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
I don't see any error with this line `, json_query(b2b_ecommerce_b2breceipt.b2breceipt_data, 'lax $. req_reference_number' omit quotes) as req_reference_number`. It produces the correct req_reference_number. Were you running the same code?

2023-08-02 13:07 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
> +- name: int__mitxpro__ecommerce_combinedcoupons
I've added tests to the fields and reuploaded

2023-08-02 13:08 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
yes the sql can run like that but the pre-commit doesn't like that code and throws an error

2023-08-02 16:40 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
sqlfluff throws a validation error for this line because of the reference to `b2b_ecommerce_b2breceipt.b2breceipt_data`. The subquery b2b_coupon_fields is doing a lot of joins on top of extracting a field from one of the tables, which sqlfluff didn't like.  As mentioned, in my opinion, it's best to add this field to staging to be able to reuse it. Alternatively, you can put that at the top when you import this model, so that in b2b_coupon_fields just reference this new field.
```
, b2b_ecommerce_b2breceipt as (
    select
        b2border_id
        , json_query(b2breceipt_data, 'lax $. req_reference_number' omit quotes) as req_reference_number
    from {{ ref('int__mitxpro__b2becommerce_b2breceipt') }}
)
```

2023-08-03 11:57 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_combinedcoupons.sql
> +        ) as req_reference_number
I made this change

2023-08-03 12:16 UTC, KatelynGit commented
All the issues mentioned above have been addressed and the newly designed table is available to query

2023-08-03 14:38 UTC, KatelynGit commented
I've fixed the error it was being caused by 2 strange records in the data

2023-08-03 15:02 UTC, abeglova commented
I checked and the bi report has 21542 but your report has 24038. Do you know where the extra rows are coming from?

2023-08-03 15:20 UTC, KatelynGit commented
I believe I'm using more left joins where the report has inner joins and it is causing different counts

2023-08-03 15:24 UTC, rachellougee reviewed
There are still dups that need to be looked into, especially the unique fields for this table.

2023-12-11 12:50 UTC, KatelynGit commented
### a new PR has been opened and competed for combined coupon work

2023-12-11 12:50 UTC, closed without merging