Fix for issue 1908 to populate parent run id's more consistently
mitodl/ol-data-platform pull request #814
Opened 2023-08-29 18:38 UTC by KatelynGit

# What are the relevant tickets?
https://github.com/mitodl/hq/issues/1908

# Description (What does it do?)
changed the join to remove int__mitxpro__coursesinprogram and join directly to programs to pull the product parent run id field

# Screenshots (if appropriate):
see relevant ticket

# How can this be tested?
Run the following commands against your schema or QA
Run dbt build --select marts.mitxpro if you have all models, otherwise add + in front of marts.mitxpro to run upstream models

2023-08-29 20:37 UTC, rachellougee reviewed
Query looks fine, but we need to update the test https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml#L50 since now there won't be multiple `product_parent_run_id` if we are using program in courses model

2023-08-29 20:53 UTC, rachellougee commented
Also can you confirm if this is changed? because the new code does not have run id on `program-v1:xPRO+SysEngx`

> Product Parent Run: ID which includes the Run #. For Example, the Product Parent Run of course-v1:xPRO+SysEngx4+R18 is program-v1:xPRO+SysEngx+R18.

2023-08-31 14:27 UTC, KatelynGit commented
> Query looks fine, but we need to update the test https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml#L50 since now there won't be multiple `product_parent_run_id` if we are using program in courses model

Good catch I've changed the tests to remove product_parent_run_id from the unique test

2023-08-31 14:28 UTC, KatelynGit commented
> Also can you confirm if this is changed? because the new code does not have run id on `program-v1:xPRO+SysEngx`
> 
> > Product Parent Run: ID which includes the Run #. For Example, the Product Parent Run of course-v1:xPRO+SysEngx4+R18 is program-v1:xPRO+SysEngx+R18.

Per Bon's screenshot it looks like he wasn't anticipating run id's as part of that field so I left if off.

2023-08-31 15:21 UTC, rachellougee requested changes
I would suggest double-checking the requirement for `product_parent_run_id` before implementing the changes, so there is no confusing here. Per @cachob , this is still the same

> Product Parent Run: ID which includes the Run #. For Example, the Product Parent Run of course-v1:xPRO+SysEngx4+R18 is program-v1:xPRO+SysEngx+R18.

2023-08-31 15:21 UTC, rachellougee commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productlist.sql
> +    , programs.program_readable_id as product_parent_run_id
We still need courserun_tag to product_parent_run_id, the requirement for this is still the same

2023-08-31 19:15 UTC, rachellougee approved these changes

2023-08-31 20:05 UTC, merged