xPRO order data mart
mitodl/ol-data-platform pull request #817
Opened 2023-09-01 11:44 UTC by KatelynGit

# What are the relevant tickets?
https://github.com/mitodl/hq/issues/1803

# Description (What does it do?)
This will add one new table the contains b2b orders and regular orders for xPRO. The new table name is - int__mitxpro__ecommerce_allorders

# How can this be tested?
Run the following commands against your schema or QA
Run dbt build --select intermediate.mitxpro if you have all models, otherwise add + in front of intermediate.mitxpro to run upstream models

2023-09-08 16:56 UTC, pdpinch commented
Is it possible to review a sample of this data?

2023-09-08 16:58 UTC, pdpinch commented
I'm not sure if this is a dumb question, but the PR title says data mart, but the PR files are named intermediate.

2023-09-08 17:32 UTC, KatelynGit commented
> I'm not sure if this is a dumb question, but the PR title says data mart, but the PR files are named intermediate.

I've changed the title the PR good catch

> Is it possible to review a sample of this data?

To view the data you can run:

select  *
from ol_warehouse_production_kdelaney_intermediate.int__mitxpro__ecommerce_allorders

But I can also send you the data in a file too just let me know if that's easier/better

2023-09-08 20:21 UTC, rachellougee reviewed
I've reviewed b2b orders, data look good but I had comments about source of some b2b fields and confusion.

2023-09-08 21:49 UTC, pdpinch commented
Will there be a separate PR for the mart version? I have some thoughts about simplifying this in the mart, if possible (for example, removing foreign key ids and just de-normalizing all the data)

2023-09-08 21:51 UTC, pdpinch commented
> To view the data you can run:
> select * from ol_warehouse_production_kdelaney_intermediate.int__mitxpro__ecommerce_allorders

Run it where?

2023-09-11 11:07 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        , b2becommerce_b2border.product_type as product_type
I've changed this so the product_id is actually pulling from the b2borders table for b2b orders. I think this should resolve this issue.

2023-09-11 11:10 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
> +    description: boolean, when an order uses a coupon this field will be 'Y' otherwise
is b2bcouponredemption a table? if so I couldn't find it.  In this case we're pulling redeemed info from ecommerce_couponredemption for both b2b and regular coupons similar to other coupon/order reports published in the past including https://bi.odl.mit.edu/queries/983/source.

2023-09-11 11:10 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        on ecommerce_order.order_purchaser_user_id = users.user_id
I've removed this join

2023-09-11 11:40 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +)
I've added this flag to the coupon version table

2023-09-11 11:42 UTC, KatelynGit commented
> Will there be a separate PR for the mart version? I have some thoughts about simplifying this in the mart, if possible (for example, removing foreign key ids and just de-normalizing all the data)

Yes, For the mart version we could have everything not just mitxpro. We could also denormalize it. 

> > To view the data you can run:
> > select * from ol_warehouse_production_kdelaney_intermediate.int__mitxpro__ecommerce_allorders
> 
> Run it where?

in starburt- https://mitol.galaxy.starburst.io/query-editor

2023-09-13 18:56 UTC, rachellougee approved these changes
LGTM. Thanks for the changes

2023-09-13 18:56 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
> +    description: boolean, when an order uses a coupon this field will be 'Y' otherwise
Per discussion I meant `raw__xpro__app__postgres__b2b_ecommerce_b2bcouponredemption`. Looks like we haven't staged it, so was wondering if we need it to track b2b coupon is redeemed or not

2023-09-21 17:07 UTC, KatelynGit commented
@rachellougee I've added the new int b2b_ecommerce_b2bcouponredemption table as a source here. can  you take a look at the new join? thanks

2023-09-21 19:27 UTC, rachellougee requested changes
I left a couple of comments, please review.

2023-09-21 19:27 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +    left join ecommerce_couponversion
This join is no longer used, can you confirm if any other join can be removed?

2023-09-21 19:27 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        on b2becommerce_b2border.b2border_id = b2becommerce_b2bcouponredemption.b2border_id
`b2bcouponredemption` and `b2border` joins should be on `b2border_id` and `b2bcoupon_id`

2023-09-21 19:27 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        , case when ecommerce_couponredemption.couponredemption_id is not null then 'Y' end as redeemed
Per discussion, we normally use true or false instead of 'Y'. If you can update it to use true or false, that'd be great.  Same with `int__mitxpro__ecommerce_couponversion`

2023-09-22 12:08 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
> +    description: boolean, when an order uses a coupon this field will be 'Y' otherwise
I've added this table as a souce

2023-09-22 12:12 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +    left join ecommerce_couponversion
I've removed this one it and it looks like all other joins are still necessary

2023-09-22 12:13 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        on b2becommerce_b2border.b2border_id = b2becommerce_b2bcouponredemption.b2border_id
I've changed it. At the moment the data results are the same regardless of joining on just order or both but from a logical standpoint I understand adding it.

2023-09-22 12:14 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        , case when ecommerce_couponredemption.couponredemption_id is not null then 'Y' end as redeemed
this is changed.  Any reason we usually use boolean instead of Y/N?

2023-09-22 13:17 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        on b2becommerce_b2border.b2border_id = b2becommerce_b2bcouponredemption.b2border_id
I agree, but just curious how do you decide what to join on? So we would need to have a understanding of table schema in order to join together, but that's why we added uniqueness to each model so we know what to join. For this specific table, you added uniqueness `["b2border_id", "b2bcoupon_id"]` https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml#L30, that signals what to join on

If you think there is anything we can improve, feel free to suggest and improve the process, so we

2023-09-22 13:29 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        , case when ecommerce_couponredemption.couponredemption_id is not null then 'Y' end as redeemed
We probably should update our documentation to make it clear. The reason I can think of is to make sure column values are readable and have meaningful values mentioned in https://learning.oreilly.com/library/view/the-informed-company/9781119748007/c10.xhtml#head-2-3. In my opinion Y/N is ambiguous. It's better to use true/false or even Yes/No. But we have been using true or false in all other models, so its good to be consistent.

2023-09-22 13:38 UTC, rachellougee approved these changes

2023-09-22 14:01 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        , case when ecommerce_couponredemption.couponredemption_id is not null then 'Y' end as redeemed
that makes sense thanks!

2023-09-22 14:07 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql
> +        on b2becommerce_b2border.b2border_id = b2becommerce_b2bcouponredemption.b2border_id
Yes that's true the uniqueness test is helpful for choosing what fields to join on.  Usually I'll try adding the table to the query and seeing how it affects the counts to understand the cardinality like if it's 1:1, 1:many, etc. as well

2023-09-22 14:09 UTC, merged