add MITx program report to staging and intermediate
mitodl/ol-data-platform pull request #870
Opened 2023-10-13 20:42 UTC by rachellougee

# What are the relevant tickets?

part of https://github.com/mitodl/ol-data-platform/issues/852

# Description (What does it do?)

Adds `stg__edxorg__s3__program_learner_report` and `int__edxorg__mitx_program_certificates`, which are deduped from `raw__edxorg__program_learner_report`

It doesn't replace the MicroMasters program data in `__micromasters_program_certificates_non_dedp` yet as we need to figure out the discrepancies first

# How can this be tested?

```
dbt build --select stg__edxorg__s3__program_learner_report
dbt build --select int__edxorg__mitx_program_certificates
```

2023-10-16 21:22 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/_edxorg_sources.yml
> +  - name: raw__edxorg__program_learner_report
@pdpinch Can you review these field definitions to see if it's what you expected?

2023-10-17 13:24 UTC, pdpinch commented
I looked through my inbox and found a PDF that documents the field definitions. Let me know if this helps, or just raises more questions.
 
[Program Console - Program Data Reports Guide.pdf](https://github.com/mitodl/ol-data-platform/files/12929374/Program.Console.-.Program.Data.Reports.Guide.2.pdf)

2023-10-17 15:16 UTC, rachellougee commented
@pdpinch Perfect. That explains all the fields definition.

2023-10-17 19:38 UTC, abeglova requested changes
Back to you with some comments. Also the refreshing stg__edxorg__s3__program_learner_report has been running for about 30 min now, even though I changed the host on dev_production to  host: mitol-ol-data-lake-qa-0.trino.galaxy.starburst.io. Not sure if that's expected

2023-10-17 19:38 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +        , cast(completed as boolean) as completed_course
Should this be course_is_completed to match our normal naming scheme for booleans?

2023-10-17 19:38 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +        , cast(completed as boolean) as completed_course
Same for other booleans in this table

2023-10-17 19:38 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
Is there a typo? You are changing 'Finance MIT' to 'Finance'
And 'Finance' to 'MIT Finance' . Should both be changed to  'MIT Finance'?

2023-10-17 19:38 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +                regexp_replace("date completed", '(\d{4}-\d{2}-\d{2})[ ](\d{2}:\d{2}:\d{2})[ ]Z', '$1T$2Z') --noqa: CV10,LT05
Can you use `date_parse(` here instead of `regexp_replace(`?

2023-10-17 19:39 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
Or is the issue that you are trying to make sure the program titles are different for different program uuids?

2023-10-17 19:49 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
No, its not typo. As you can see, Finance comes with 3 different names and 2 different UUID. My understanding is that  `c22ff74a-6bec-4357-b941-d3eaf56966c7` is MIT Finance (new version), `50e72d85dfc7402ba3173ff51e11a748` is Finance. So this ensures title are consistent with UUID.
![Pasted Graphic](https://github.com/mitodl/ol-data-platform/assets/3138890/b5e0eafe-5e26-4ca9-8057-10b079b96bdd)

2023-10-17 19:51 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
So maybe you can remove the `"program title" =` part of the line and just keep the uuid part? If the title is already correct already that's  fine

2023-10-17 19:52 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
Just so it's clearer that you're assigning titles based on uuid

2023-10-17 21:40 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance' and "program uuid" like '%e11a748' then 'MIT Finance' --noqa: CV10
pre-commit didn't like when I commit the whole UUID, so I used the partial match but didn't want to run into collision with partial uuid. But now I think about it, it should be fine to just keep the uuid part. I updated it

2023-10-17 21:41 UTC, rachellougee commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +                regexp_replace("date completed", '(\d{4}-\d{2}-\d{2})[ ](\d{2}:\d{2}:\d{2})[ ]Z', '$1T$2Z') --noqa: CV10,LT05
done, its actually much shorter to use date_parse. Thanks

2023-10-17 21:43 UTC, rachellougee commented
Per discussion, this raw table is very large so it needs to run under `mitol-ol-data-lake-production.trino.galaxy.starburst.io`. It should be less than 5 mins. 
@abeglova Addressed your comments. Please take a look when you get a chance.

2023-10-18 14:13 UTC, abeglova commented on src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__program_learner_report.sql
> +            when "program title" = 'Finance MIT' and "program uuid" like '%56966c7' then 'Finance' --noqa: CV10
Can you update .pre-commit-config.yaml to ignore CV10? the syntax should be 
```
[sqlfluff]
exclude_rules = CV10
```
https://docs.sqlfluff.com/en/stable/configuration.html

2023-10-18 14:14 UTC, abeglova approved these changes
LGTM - although i think you should just disable CV10 instead of having so may noqa comments

2023-10-18 16:17 UTC, abeglova approved these changes

2023-10-18 17:07 UTC, merged