feat: add courseware format
mitodl/ol-data-platform pull request #880
Opened 2023-10-18 08:39 UTC by asadali145

# What are the relevant tickets?

Fixes https://github.com/mitodl/mitxpro/issues/2611

# Description (What does it do?)

Adds courseware format added in https://github.com/mitodl/mitxpro/issues/2611.

# How can this be tested?

Will add testing instructions once the xPro PR is merged.

2023-10-20 13:58 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
> +    description: str, format of the course (Online, Other)
Will there be blank? if not, then I would suggest
```suggestion
    description: str, format of the program or course (Online, Other)
    tests:
    - not_null
    - accepted_values:
        values: ['Online', 'Other']
```

2023-10-20 14:15 UTC, rachellougee requested changes
I left a couple of comments. Also, it doesn't seem like this two fields are in our data platform yet? We will need to add them in the raw before merging.

2023-10-20 14:15 UTC, rachellougee commented on src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml
> +  - name: format
This name doesn't match with what it's added in the mart

2023-10-20 14:15 UTC, rachellougee commented on src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productlist.sql
> +    , courses.cms_coursepage_format as course_format
@KatelynGit I assume you need this field in the mart?

2023-10-23 07:17 UTC, asadali145 commented
Review changes resolved in 767c7f290816c9e491dc3a4bc2dfa28c0102c466.

2023-10-26 13:57 UTC, rachellougee approved these changes
Code looks good. But I would suggest making sure fields exist in raw tables on production and run tests before merging as I still don't see `format` added to these 4 raw tables.

2023-12-05 08:38 UTC, asadali145 commented
@rachellougee I have tried to test this PR multiple times but I am getting an error that I wasn't getting when I created this PR. Do you know any workarounds for this issue?
I have tried:

- `dbt build -s +int__mitxpro__courses --vars 'schema_suffix: asad' --target dev_production`
- `dbt build -s +int__mitxpro__courses --vars 'schema_suffix: asad'`

<img width="1738" alt="Screen Shot 2023-12-05 at 1 36 22 PM" src="https://github.com/mitodl/ol-data-platform/assets/52656433/c2815f8b-50c5-4afd-8b10-237d691129eb">

2023-12-05 14:59 UTC, rachellougee commented
@asadali145 The error you are getting are unrelated to your PR but it's related to relationships tests in [this line](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml#L1330), that test has been always there.  So `dbt build -s +int__mitxpro__courses` will run all the tests related to this model, but it doesn't seem to run `dbt run ` on all the related models used in the test. In this case, you have never ran `int__mitxpro__courserun_certificates` and 
`int__mitxpro__courserun_grades` under your schema

To workaround that, you can run 
- these two separate commands since you only need to test stage and intermediate models that you modified
```
dbt build --select stg__mitxpro__app__postgres__cms_coursepage --vars 'schema_suffix: asad' --target dev_production
dbt build --select  int__mitxpro__courses --vars 'schema_suffix: asad' --target dev_production
```
- `dbt build --select @int__mitxpro__courses --vars 'schema_suffix: asad' --target dev_production`. But this will run the parents of the children of the courses model, which takes long time and may not be necessary https://docs.getdbt.com/reference/node-selection/graph-operators

2023-12-05 15:09 UTC, rachellougee commented
@asadali145 Also, I just ran this PR changes under my schema. It works fine, so I think you can merge it now.

2023-12-05 15:47 UTC, asadali145 commented
@rachellougee Thanks for your help. Merging this PR.

2023-12-05 15:47 UTC, merged