add new email optout table to staging
mitodl/ol-data-platform pull request #899
Opened 2023-10-27 15:58 UTC by KatelynGit

# What are the relevant tickets?
https://github.com/mitodl/hq/issues/1545

# Description (What does it do?)
adds table stg__mitxonline__openedx__mysql__bulk_email_optout from raw to staging

# How can this be tested?
Run the following commands against your schema or QA
Run dbt build --select staging.mitxonline if you have all models, otherwise add + in front of  staging.mitxonline to run upstream models

2023-10-30 13:03 UTC, rachellougee requested changes
Please review the fields in this table. I think you might got confused these with user_id and course_id from django app

2023-10-30 13:03 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxonline/_stg_mitxonline__models.yml
> +    description: int, primary key representing a single MITx Online course
same comment as above

2023-10-30 13:03 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__bulk_email_optout.sql
> +        , user_id
this should be `openedx_user_id`. Please take a look at `stg__mitxonline__openedx__mysql__auth_user`

2023-10-30 13:03 UTC, rachellougee commented on src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__bulk_email_optout.sql
> +        , course_id
This should be courserun_readable_id, same reference to `stg__mitxonline__app__postgres__courses_courserun`. courserun_readable_id

2023-10-30 15:12 UTC, KatelynGit commented on src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__bulk_email_optout.sql
> +        , user_id
changed the field name

2023-10-30 15:12 UTC, KatelynGit commented on src/ol_dbt/models/staging/mitxonline/_mitxonline__sources.yml
> +      description: int, foreign key to courses_course representing a single MITx Online
updated the description

2023-10-30 16:44 UTC, rachellougee reviewed
For staging table, we should indicate fields that are not supposed to be null and unique fields. Otherwise, it would be hard to use it in intermediate without looking at data.

2023-10-31 14:36 UTC, KatelynGit commented on src/ol_dbt/models/staging/mitxonline/_stg_mitxonline__models.yml
> +    description: int, unique ID for each user on the MITx Online platform
i've added this

2023-10-31 14:37 UTC, KatelynGit commented on src/ol_dbt/models/staging/mitxonline/_stg_mitxonline__models.yml
> +    description: string, unique ID representing a single MITx Online course run
added this as well

2023-10-31 15:09 UTC, rachellougee approved these changes

2023-10-31 15:27 UTC, merged