new combined orders mart table
mitodl/ol-data-platform pull request #938
Opened 2023-12-04 12:02 UTC by KatelynGit

# What are the relevant tickets?
https://github.com/mitodl/hq/issues/2425

# Description (What does it do?)
creates table marts__combined__orders from mitxonline, mixpro, and bootcamp data

# How can this be tested?
dbt build --select +marts__combined__orders

2023-12-04 14:03 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as user_id
sorry I don't get why user_id would be null for xPro

2023-12-04 14:04 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as order_total_price_paid
xPro orders don't have total_price_paid? that seems strange

2023-12-04 14:07 UTC, rachellougee requested changes
I left a few comments, which I don't quite understand all the null for this combined orders. Most of these fields should have data populated.

2023-12-05 21:35 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +- name: int__mitxpro__ecommerce_allorders
i've fixed this now

2023-12-05 21:36 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as courserun_id
i've populated it now

2023-12-05 21:36 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as user_id
i've populated it now

2023-12-05 21:36 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as order_total_price_paid
i've populated it now

2023-12-05 21:36 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined__orders.sql
> +        , null as user_email
i've populated it now

2023-12-05 21:37 UTC, KatelynGit commented
> I left a few comments, which I don't quite understand all the null for this combined orders. Most of these fields should have data populated.

Thanks @rachellougee! I've made changes per your comments

2023-12-06 15:22 UTC, rachellougee reviewed
Beside these comments, i also can't run this mart as it appears some issues with schema naming conflicts

@KatelynGit were you able to run this new mart without issue?

2023-12-07 13:25 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/marts__combined_orders.sql
> +        on mitxpro__ecommerce_allorders.b2border_id = mitxpro__b2becommerce_b2border.b2border_id
the problem is some of the fields aren't there in allorders so I needed to use those other tables for now

2023-12-07 13:26 UTC, KatelynGit commented
> Beside these comments, i also can't run this mart as it appears some issues with schema and CTE name
> 
> @KatelynGit were you able to run this new mart without issue?

@rachellougee  sorry about that - can you try again. I believe it should work now

2023-12-07 16:16 UTC, KatelynGit commented on src/ol_dbt/models/marts/combined/_marts__combined__models.yml
> +    description: int, foreign key to the user table
I've added a unique test as well

2023-12-07 17:21 UTC, rachellougee reviewed
@KatelynGit I am getting error on the duplicates for xpro. It looks like some of these duplicates are from using different coupon.

```16:57:41  Failure in test dbt_expectations_expect_compound_columns_to_be_unique_marts__combined__orders_order_id__line_id__b2b_indicator__platform (models/marts/combined/_marts__combined__models.yml)
16:57:41    Got 292 results, configured to fail if >10
```

Can you double check these records and run a build after making a change? Additionally I don't know these fields are enough to be in combined mart for orders since it doesn't have coupon, receipt/payment data in it. But that can be another subject.

2023-12-07 17:24 UTC, rachellougee commented on src/ol_dbt/models/marts/combined/marts__combined_orders.sql
> +        on mitxpro__ecommerce_allorders.b2border_id = mitxpro__b2becommerce_b2border.b2border_id
I am not sure if I understand your comment, my point was that this join and additional table import can be totally eliminated if `order_purchaser_user_id`, `order_total_price_paid`, `b2border_total_price` are added in int__mitxpro__ecommerce_allorders since it's already [joined all these tables](https://github.com/mitodl/ol-data-platform/blob/main/src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__ecommerce_allorders.sql#L62-L99). Also, these fields exist in MITx Online intermediate orders table.

That's not to say we can't do join in mart as there are many cases we will need additional joins and aggregation in mart. Unfortunately I just don't think this is not one of cases. With that said, it's up to you.

2023-12-07 19:51 UTC, KatelynGit commented
> @KatelynGit I am getting error on the duplicates for xpro. It looks like some of these duplicates are from using different coupon.
> 
> ```
> 16:57:41  Failure in test dbt_expectations_expect_compound_columns_to_be_unique_marts__combined__orders_order_id__line_id__b2b_indicator__platform (models/marts/combined/_marts__combined__models.yml)
> 16:57:41    Got 292 results, configured to fail if >10
> ```
> 
> Can you double check these records and run a build when making a change? Additionally I don't know these fields are enough to be in combined mart for orders since it doesn't have coupon, receipt/payment data in it. But that can be another subject.

I've added coupon_id and name to the table and added them to the unique constraint it seems to have fixed the issue

2023-12-20 15:39 UTC, rachellougee approved these changes
The unique test runs fine now

2023-12-20 15:41 UTC, merged