create course engagement mart and upstream model
mitodl/ol-data-platform pull request #947
Opened 2023-12-12 16:04 UTC by rachellougee

# What are the relevant tickets?

https://github.com/mitodl/hq/issues/3120 and additional intermediate models in [this spreadsheet](https://docs.google.com/spreadsheets/d/1_4z3KWh3n0XGDEAKA8DrIeKfxvUSNeX8-CVDibN7Q5A/edit#gid=1756599030)

# Description (What does it do?)

 - creating `int__mitxonline__user_courseactivity_discussion` and `int__mitxonline__user_courseactivity_daily` to simplify the mart
 - Updating `int__mitxonline__user_courseactivity_video` to include additional video events like `complete_video`, `seek_video` etc that are useful for reports
 - creating `mart__mitxonline_weekly_course_engagement` that includes week_start_date, week_end_date, courserun_readable_id, unique_users, unique_tried_problem_users, unique_played_video_users and unique_participated_discussion_users

# How can this be tested?

Update `host` to  `mitol-ol-data-lake-production.trino.galaxy.starburst.io` under dev_production target in your profile.yml to be able to run large model

then run
```
dbt build +marts__mitxonline_weekly_course_engagements  --target dev_production
```

2023-12-13 19:01 UTC, rachellougee commented on src/ol_dbt/models/marts/mitxonline/marts__mitxonline_weekly_course_engagements.sql
> +{% set week_start_date= '2022-01-02' %}
Discussed with Kate, we decide to create daily course engagement mart that is unique on username+courserun_readable_id+date . We can then aggregate weekly on Preset if needed

2023-12-14 14:32 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      events edx.video.played, edx.video.paused, etc.
Would it be appropriate, and easier, to link to the open edX documentation for these events?

2023-12-14 14:32 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, URL that generated this event
Is this a URL or a path?

2023-12-14 14:33 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, hash code for the video being watched. This value is last part
```suggestion
    description: str, hash code for the video being watched. This value is the last part
```

2023-12-14 16:37 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      events edx.video.played, edx.video.paused, etc.
The documentation link https://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/tracking_logs/student_event_types.html#video-interaction-events is too long to add in description here as pre-commit would try to format it to new line and that might not be readable. I also noticed that not all video events are documented there. e.g. complete_video

2023-12-14 16:38 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, URL that generated this event
This field is the relative url of the page. I realized that for video events, `useractivity_page_url` is more useful here, so I updated that. But not every event has useractivity_page_url field populated.

2023-12-14 16:38 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, hash code for the video being watched. This value is last part
updated

2023-12-14 16:40 UTC, pdpinch requested changes
Sorry my review came in bits and pieces.

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, URL that generated this event
URL or path?

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      The values are either browser or mobile for this event
Is this browser or _mobile app_? Can we note that mitxonline doesn't have a mobile app at this time (but edx.org does)

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      etc.
Can we link to open edX docs for these events?

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      Maybe Null for edx.forum.searched event
```suggestion
      May be Null for edx.forum.searched event
```

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +    description: str, title for the specific discussion post. Maybe Null for edx.forum.searched
```suggestion
    description: str, title for the specific discussion post. May be Null for edx.forum.searched
```

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      Value is the last part of 'coursestructure_block_id' string. Maybe Null for
```suggestion
      Value is the last part of 'coursestructure_block_id' string. May be Null for
```

2023-12-14 16:40 UTC, pdpinch commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      ["Community TA", "Student"].
Do we know the complete set of possible roles? Can we link to some documentation for this?

2023-12-14 18:14 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      The values are either browser or mobile for this event
The discussion event can only be from server, so I updated the description here. I noted mitxonline doesn't have a mobile app in video event https://github.com/mitodl/ol-data-platform/pull/947/files#diff-ed9000c0ae953ef078e3e7c9b3f50c4d2d244836cd1728a92a51e3a855be902fR1382 as that's emitted from client side.

2023-12-14 18:23 UTC, rachellougee commented
@pdpinch Thanks for the review. I've updated description per your comments

2023-12-14 18:24 UTC, rachellougee commented on src/ol_dbt/models/intermediate/mitxonline/_int_mitxonline__models.yml
> +      events edx.video.played, edx.video.paused, etc.
I added link anyway.

2023-12-18 22:06 UTC, KatelynGit approved these changes
I ran the dbt build and there were no errors. I also tested the table for things like blanks and to make sure we weren't duplicating records or dropping records from the source tables when creating it and it all looked good. I think this design works much better and is more flexible than the weekly one we originally discussed I'm signing off.

2023-12-19 03:48 UTC, pdpinch approved these changes
lgtm

2023-12-19 14:14 UTC, merged