add micromasters int and mart tables for exam grades
mitodl/ol-data-platform pull request #987
Opened 2024-01-26 16:42 UTC by KatelynGit

### What are the relevant tickets?
https://github.com/mitodl/hq/issues/3431

### Description (What does it do?)
Creates the marts__micromasters_exam_grades and int__micromasters__exam_grades tables

### How can this be tested?
dbt build --select +marts__micromasters_exam_grades

2024-01-29 14:55 UTC, rachellougee reviewed
Mostly feedback on field description and naming for the mart.

2024-01-29 14:55 UTC, rachellougee commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, user full name on edX.org or MITxOnline. Very small number of
Looking at the query, we are getting `user_full_name` from __micromasters__users, so I am not sure why it says from edX.org or MITxOnline? Can we double check?

2024-01-29 14:55 UTC, rachellougee commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, user full name on edX.org or MITxOnline. Very small number of
Same comments as `user_address_country` and `user_email`

2024-01-29 14:55 UTC, rachellougee commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +      enrolled for the course
Beside the description, I think user_email can't be null?

2024-01-29 14:55 UTC, rachellougee commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: int, sequential ID representing a DEDP proctor exam grade
Can we add some test to these fields? null and unique keys? Staging table doesn't indicate that, but I think `grades_proctoredexamgrade` table is static now since it has stopped updating since 2022-09. So we should be able to find out the uniqueness in this table

2024-01-29 14:55 UTC, rachellougee commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +- name: marts__micromasters_exam_grades
Does it make sense to specify DEDP for the mart name? This table is for old DEDP and has no other MicroMasters exam grades, so i think we should be clear about that in the name?

2024-01-29 15:03 UTC, rachellougee commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, user full name on edX.org or MITxOnline. Very small number of
These profile fields are sourced from `stg__micromasters__app__postgres__profiles_profile`, so these come directly from MicroMasters

2024-01-29 19:10 UTC, rachellougee commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +- name: marts__micromasters_exam_grades
@pdpinch not sure what you think of the naming this mart as I believe this is specific for DEDP proctor exam that was last updated in 2022-07

2024-01-30 13:32 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: int, sequential ID representing a DEDP proctor exam grade
added tests

2024-01-30 13:33 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, user full name on edX.org or MITxOnline. Very small number of
I changed these descriptions

2024-01-30 13:33 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +      enrolled for the course
added test

2024-01-30 13:33 UTC, KatelynGit commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +- name: marts__micromasters_exam_grades
changed the table names

2024-01-30 16:27 UTC, pdpinch requested changes

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +- name: int__micromasters__exam_grades_old_data
```suggestion
- name: int__micromasters__dedp_proctored_exam_grades
```

I agree with Rachel that this table name could be clearer. If this is too long, we could remove the word `proctored`

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, edX course number
It would be useful to have an example in the description here.

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, country code provided by the user from micromasters
This field seems out of place to me here. Is there a reason why we have it?

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +  description: DEDP proctor exam grades stored in MicroMasters database
We could mention in the description that there haven't been any new proctored exam grades since `insert date`

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +  description: DEDP proctor exam grades stored in MicroMasters database
name and description should correspond to the intermediate table name and description.

2024-01-30 16:27 UTC, pdpinch commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +  description: DEDP proctor exam grades stored in MicroMasters database
That said... I'm not 100% sure we need a mart for this table. If we meet with the DEDP team and learn that they would prefer this data a different way -- like maybe as part of the certificate mart -- can we remove this later?

2024-02-05 13:09 UTC, KatelynGit commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +- name: marts__micromasters_exam_grades
i changed the name

2024-02-05 13:51 UTC, pdpinch commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, edX course number for example CTL.SC4x or 15.415.1x
since this table only applies to DEDP, we might as well use DEDP examples. 

```suggestion
    description: str, edX course number for example 14.73x or JPAL102x
```

2024-02-06 15:37 UTC, rachellougee approved these changes

2024-02-29 14:01 UTC, pdpinch requested changes

2024-02-29 14:01 UTC, pdpinch commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +    description: str, current user email on MicroMasters
Same comment as above. If this email is coming from micromasters we should make that clear. 

Is it possible to include a mitxonline email as well, for those situations when they are different?

2024-02-29 14:01 UTC, pdpinch commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +    description: timestamp, date and time for the exam
Same comment as above. Is this the timestamp for when the learner took the exam? If so, make it clearer.

2024-02-29 19:59 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: str, current user email on micromasters
I've changed this to user_micromasters_email

2024-02-29 20:00 UTC, KatelynGit commented on src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
> +    description: timestamp, date and time for the exam
I added to the description that it's the date the learner took the exam

2024-02-29 20:00 UTC, KatelynGit commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +    description: str, edX course number
I've changed this to the suggested description

2024-02-29 20:01 UTC, KatelynGit commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +    description: str, current user email on MicroMasters
I've added the mixonline email and changed the other field to contain the word micromasters

2024-02-29 20:01 UTC, KatelynGit commented on src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
> +    description: timestamp, date and time for the exam
I've changed this per the suggestion

2024-02-29 20:10 UTC, KatelynGit commented
@pdpinch I think this should be all set for sign off with the changes but let me know if not

2024-03-01 18:56 UTC, pdpinch approved these changes

2024-03-01 19:01 UTC, merged